CHECKINTERVAL_MINUTES = 30
CHECKINTERVAL_SECOND = 15
RELIABLE_DAYS = 3

SERVER_NAME = 'ANGUS'
DATABASE_NAME = 'HKJC_Odds'
USER_NAME = 'sa'
PASSWORD = '2036'

DRIVER_NAME = 'SQL SERVER'
CONNECTION_STRING = f"""
    DRIVER={{{DRIVER_NAME}}};
    SERVER={SERVER_NAME};
    DATABASE={DATABASE_NAME};
    PORT=49172;
    Trust_Connection=yes;
    uid={USER_NAME};
    pwd={PASSWORD};
"""

TOKEN = '6053673668:AAGqaWrfrALlOF6XT7g2aNfONW7jjyXFRZk'
GROUP_ID = -1002143736198

